name: Data Fusion Lab
url: https://datafusionlab.org

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: phd
    name: Ph.D. Graduates
  - key: masters
    name: Masters Graduates
  - key: director
    name: Director
  - key: affiliated
    name: Affiliated Faculty

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: Publications
    link: /publications

# BIBTEX SETTINGS
scholar:
  style:  _bibliography/ieee_custom
  locale: en
  sort_by: author
  order: ascending
  source: ./_bibliography
  bibliography: "*.bib"
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   "[bib]"
  query: "@*"
  repository: ./publications/
